name: Build Keyboard Master

on:
  push:
    tags:
      - 'v*'
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build for Mac ARM
        run: npx electron-builder --mac --publish always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: false
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: keyboard-master-mac-arm
          path: dist/

  build-windows:
    runs-on: windows-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: '20'
      
      - name: Install dependencies
        run: npm install

      - name: Build & Publish for Windows
        run: npx electron-builder --win --publish always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: keyboard-master-windows
          path: dist/
  
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: '20'
      
      - name: Install dependencies
        run: npm install

      - name: Build for Linux
        run: npx electron-builder --linux --publish always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: keyboard-master-linux
          path: dist/